project_id = "fglpzxtrvipizoymwteg"

[functions]
  [functions.admin-seed-demo]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
