-- Seed default_tasks from the seed_default_tasks function body (idempotent: skip when already populated)
DO $$
BEGIN
  IF (SELECT count(*) FROM public.default_tasks) > 0 THEN
    RETURN;
  END IF;

  INSERT INTO public.default_tasks (title, category, priority, due_period, sort_order, action_label, action_url) VALUES
  ('Vamos casar! E agora?', 'planejamento', 'recommended', '10-12 meses', 1, NULL, NULL),
  ('Primeiro passo: baixar o App!', 'planejamento', 'recommended', '10-12 meses', 2, NULL, NULL),
  ('Escolher a data e o tipo de casamento', 'planejamento', 'essential', '10-12 meses', 3, NULL, NULL),
  ('Os noivos devem organizar tudo ou é melhor contratar um(a) cerimonialista/wedding planner?', 'planejamento', 'recommended', '10-12 meses', 4, 'Ver cerimonialistas', '/buscar?categoria=cerimonialista'),
  ('Fazer primeira lista de convidados', 'planejamento', 'essential', '10-12 meses', 5, 'Ir para convidados', '/convidados'),
  ('Vincular os perfis de Casamentos.com.br', 'planejamento', 'optional', '10-12 meses', 6, NULL, NULL),
  ('Anuncie seu casamento', 'planejamento', 'optional', '10-12 meses', 7, NULL, NULL),
  ('Quanto vamos gastar?', 'planejamento', 'essential', '10-12 meses', 8, 'Ir para orçamento', '/orcamento'),
  ('Escolher o tipo de cerimônia e o tipo de local', 'cerimonia', 'essential', '10-12 meses', 9, NULL, NULL),
  ('Confirmar o dia e a hora do evento', 'cerimonia', 'essential', '10-12 meses', 10, NULL, NULL),
  ('Buscar e contratar o Juiz de Paz e/ou Celebrante', 'cerimonia', 'essential', '10-12 meses', 11, NULL, NULL),
  ('Avaliar orçamentos e os espaços para a recepção', 'recepcao', 'essential', '10-12 meses', 12, 'Ver espaços', '/buscar?categoria=recepcao'),
  ('Reservar o espaço para a recepção', 'recepcao', 'essential', '10-12 meses', 13, NULL, NULL),
  ('Buscar e reservar o buffet ou catering', 'recepcao', 'essential', '10-12 meses', 14, 'Ver buffets', '/buscar?categoria=buffet'),
  ('Organizar as mesas dos convidados', 'recepcao', 'recommended', '10-12 meses', 15, 'Ir para convidados', '/convidados'),
  ('Hora de buscar o fotógrafo!', 'foto-video', 'essential', '10-12 meses', 16, 'Ver fotógrafos', '/buscar?categoria=fotografia'),
  ('Buscar orçamentos para a música da cerimônia', 'musica', 'recommended', '10-12 meses', 17, 'Ver músicos', '/buscar?categoria=musica'),
  ('Procurar orçamentos para uma banda ou DJ para a festa', 'musica', 'recommended', '10-12 meses', 18, 'Ver DJs e bandas', '/buscar?categoria=musica'),
  ('Pensar em atividades e na animação para a festa', 'recepcao', 'optional', '10-12 meses', 19, NULL, NULL),
  ('Tem convidados que moram longe? Hora de buscar hospedagem ou transporte para eles', 'planejamento', 'recommended', '10-12 meses', 20, NULL, NULL),
  ('Contratar o fotógrafo', 'foto-video', 'essential', '10-12 meses', 21, 'Ver fotógrafos', '/buscar?categoria=fotografia'),
  ('Contratar os músicos do casamento', 'musica', 'essential', '10-12 meses', 22, 'Ver músicos', '/buscar?categoria=musica'),
  ('Encomendar os "Save the Date" (pré-convites de casamento)', 'convites', 'recommended', '10-12 meses', 23, NULL, NULL),
  ('Fazer lista de destinos para Lua de Mel', 'lua-de-mel', 'recommended', '10-12 meses', 24, NULL, NULL),
  ('Começar a pesquisar vestidos de noiva', 'trajes', 'recommended', '7-9 meses', 25, NULL, NULL),
  ('Avisar sobre o casamento no trabalho', 'planejamento', 'recommended', '7-9 meses', 26, NULL, NULL),
  ('Começar os trâmites de documentos do casamento civil', 'legal', 'essential', '7-9 meses', 27, NULL, NULL),
  ('Começar os trâmites para o casamento religioso', 'legal', 'essential', '7-9 meses', 28, NULL, NULL),
  ('Buscar orçamentos de floristas e decoração de casamento', 'decoracao', 'essential', '7-9 meses', 29, 'Ver decoradores', '/buscar?categoria=decoracao'),
  ('Pensar em fazer algo de artesanato (DIY)', 'detalhes', 'optional', '7-9 meses', 30, NULL, NULL),
  ('Procurar estilos de buquês de noiva', 'decoracao', 'recommended', '7-9 meses', 31, NULL, NULL),
  ('Buscar as alianças', 'cerimonia', 'essential', '7-9 meses', 32, NULL, NULL),
  ('Hora de provar vestidos de noiva', 'trajes', 'essential', '7-9 meses', 33, NULL, NULL),
  ('Alugar ou comprar o vestido de noiva?', 'trajes', 'recommended', '7-9 meses', 34, NULL, NULL),
  ('E então? Como vai a organização do casamento?', 'planejamento', 'optional', '7-9 meses', 35, NULL, NULL),
  ('Encomendar o vestido de noiva', 'trajes', 'essential', '7-9 meses', 36, NULL, NULL),
  ('Provar o vestido de noiva', 'trajes', 'recommended', '7-9 meses', 37, NULL, NULL),
  ('Decidir a agência para a Lua de Mel', 'lua-de-mel', 'recommended', '7-9 meses', 38, NULL, NULL),
  ('Enviar o "Save the date"', 'convites', 'recommended', '7-9 meses', 39, NULL, NULL),
  ('Buscar orçamentos de convites de casamento', 'convites', 'recommended', '4-6 meses', 40, NULL, NULL),
  ('Escolher padrinhos, testemunhas, pajens e damas de honra', 'planejamento', 'essential', '4-6 meses', 41, NULL, NULL),
  ('Contratar florista e decoração', 'decoracao', 'essential', '4-6 meses', 42, 'Ver decoradores', '/buscar?categoria=decoracao'),
  ('Encomendar/comprar traje do noivo', 'trajes', 'essential', '4-6 meses', 43, NULL, NULL),
  ('Contratar bolo e doces', 'buffet', 'essential', '4-6 meses', 44, 'Ver confeitarias', '/buscar?categoria=buffet'),
  ('Agendar degustação do buffet', 'buffet', 'recommended', '4-6 meses', 45, NULL, NULL),
  ('Pesquisar e contratar transporte', 'logistica', 'recommended', '4-6 meses', 46, NULL, NULL),
  ('Planejar lua de mel', 'lua-de-mel', 'recommended', '4-6 meses', 47, NULL, NULL),
  ('Contratar iluminação e som', 'decoracao', 'recommended', '4-6 meses', 48, NULL, NULL),
  ('Definir o cardápio final', 'buffet', 'essential', '4-6 meses', 49, NULL, NULL),
  ('Enviar convites oficiais', 'convites', 'essential', '2-3 meses', 50, NULL, NULL),
  ('Primeira prova do vestido/traje', 'trajes', 'essential', '2-3 meses', 51, NULL, NULL),
  ('Definir votos (se personalizados)', 'cerimonia', 'optional', '2-3 meses', 52, NULL, NULL),
  ('Escolher alianças', 'cerimonia', 'essential', '2-3 meses', 53, NULL, NULL),
  ('Planejar despedida de solteiro(a)', 'eventos', 'optional', '2-3 meses', 54, NULL, NULL),
  ('Contratar cabeleireiro e maquiador', 'beleza', 'essential', '2-3 meses', 55, 'Ver profissionais', '/buscar?categoria=beleza'),
  ('Fazer teste de cabelo e maquiagem', 'beleza', 'recommended', '2-3 meses', 56, NULL, NULL),
  ('Comprar acessórios (sapatos, véu, etc)', 'trajes', 'recommended', '2-3 meses', 57, NULL, NULL),
  ('Confirmar todos os fornecedores', 'planejamento', 'essential', '2-3 meses', 58, 'Ver fornecedores', '/meus-fornecedores'),
  ('Organizar disposição das mesas', 'convidados', 'recommended', '2-3 meses', 59, 'Ir para convidados', '/convidados'),
  ('Última prova do vestido/traje', 'trajes', 'essential', 'ultimo-mes', 60, NULL, NULL),
  ('Confirmar RSVP dos convidados', 'convidados', 'essential', 'ultimo-mes', 61, 'Ir para convidados', '/convidados'),
  ('Confirmar número final de convidados com buffet', 'buffet', 'essential', 'ultimo-mes', 62, NULL, NULL),
  ('Reunião final com cerimonialista', 'planejamento', 'essential', 'ultimo-mes', 63, NULL, NULL),
  ('Preparar roteiro da cerimônia', 'cerimonia', 'essential', 'ultimo-mes', 64, NULL, NULL),
  ('Ensaio da cerimônia', 'cerimonia', 'recommended', 'ultimo-mes', 65, NULL, NULL),
  ('Organizar documentação para o casamento civil', 'legal', 'essential', 'ultimo-mes', 66, NULL, NULL),
  ('Preparar kit de emergência', 'logistica', 'recommended', 'ultimo-mes', 67, NULL, NULL),
  ('Confirmar transporte e logística', 'logistica', 'essential', 'ultimo-mes', 68, NULL, NULL),
  ('Finalizar playlist/setlist com DJ/banda', 'musica', 'recommended', 'ultimo-mes', 69, NULL, NULL),
  ('Confirmar horários com todos os fornecedores', 'planejamento', 'essential', 'ultima-semana', 70, NULL, NULL),
  ('Separar e organizar todos os pagamentos finais', 'orcamento', 'essential', 'ultima-semana', 71, 'Ir para orçamento', '/orcamento'),
  ('Embalar malas para lua de mel', 'lua-de-mel', 'recommended', 'ultima-semana', 72, NULL, NULL),
  ('Fazer spa/relaxar', 'beleza', 'optional', 'ultima-semana', 73, NULL, NULL),
  ('Preparar gorjetas e agradecimentos', 'planejamento', 'optional', 'ultima-semana', 74, NULL, NULL),
  ('Café da manhã leve e hidratação', 'dia-do-casamento', 'recommended', 'dia-do-casamento', 75, NULL, NULL),
  ('Cabelo e maquiagem', 'dia-do-casamento', 'essential', 'dia-do-casamento', 76, NULL, NULL),
  ('Verificar se alianças estão com padrinho', 'dia-do-casamento', 'essential', 'dia-do-casamento', 77, NULL, NULL),
  ('Entregar cronograma final ao cerimonialista', 'dia-do-casamento', 'essential', 'dia-do-casamento', 78, NULL, NULL),
  ('Aproveitar cada momento!', 'dia-do-casamento', 'essential', 'dia-do-casamento', 79, NULL, NULL);
END $$;